version: '3.4'

services:

  api:
    build: 
      "./api"
    hostname: api
    environment:
      DB_URL: "postgres://postgres:12345678@postgres:5432/brothers_test"
    depends_on:
      - db 
    volumes:
      - ./api:/home/node/app
    expose:
      - "80"
    # restart: always

  db:
    image: docker.io/postgres:15
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: brothers_test
    volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    # command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - "5432:5432"
    restart: always
    # networks:
    #   - front-tier
  #
  # networks:
  #   front-tier: {}
